### PR TITLE
Feature/new season endpoints

### PR DESCRIPTION
**Pull request by lyhoang080696**

### CODE REVIEW

**Comment by juho-karppinen-gofore** [comment]
The endpoints seem to reside under the /api/junior. Is this intended, or should they be under /api/admin?

**Comment by juho-karppinen-gofore** [comment]
The logic itself works and I was able to both expire and delete expired youths.

**Comment by lyhoang080696** [comment]
I also did contemplate on whether this should be in Admin or Junior, DELETE junior/:id is in Junior, even though it mark as an Admin role feature. So I come to conclusion that module does not group by user's point of view, but by server point of view, meaning the Admin module deal with CRUD of admin users while Junior deal with CRUD with Junior, instead of Admin module deal with Admin privilege and Junior deal with Junior privilege, so following that logic, these endpoint should be in Junior instead of admin. It seems the name of the module is misleading a bit. However changes to these are quite fast as well, so if you disagree we can update the code quickly.

**Review by juho-karppinen-gofore — APPROVED** [review]

**Comment by juho-karppinen-gofore** [comment]
Yeah, makes sense from that perspective. 👍

**Pull request merged**
